---
- hosts: nodes
  tasks: 
   - name: install package apache
     package:
       name: apache2
       state: present
   - name: Check apache service
     service:
       name: apache2
       state: started
   - name: update the index file
     copy:
       src: index.html
       dest: /var/www/html/index.html
